### PR TITLE
It's time to make an update :)

### PR DESCRIPTION
**Pull request by Alexays**
Ok so, in this PR, I add the ability to move the cards and save the position on Google Sync.
And also:
- When storage had no name, just print it's volume capacity. (ex: 256GB Volume)
- Updating dependencies and fixing functions for these new versions.
- Fix some typos.
- If users is on dev channel or chromium we can show available space in system card.
- Some CSS update and animations.
- Add Google Doodle

Know bugs:
- slide indicator tabs.

If anyones find other bugs tell me :)

PS: It should have been just one commit I tryed to do the best to separate the changes :(

### CODE REVIEW

**Comment by dotlouis** [comment]
Hey @Leigende, thanks a lot for your interest in cardboard. As you see I haven't updated the extension in months. But fear not, I will review your changes as soon as I have a bit of spare time.
It seems you did quite a lot :)
Thanks again I'll keep you updated !

**Comment by dotlouis** [comment]
Hey @Alexays I've started to review your changes, tell me when you think you're done with the commits :)

**Comment by Alexays** [comment]
@dotlouis Yeah ;) it's Ok now !

**Comment by dotlouis** [comment]
@Alexays Merged ! Though I'm making some style tweaks before releasing. The goal is to align the new styles with the new google material philosophy accross the `chrome://` pages.
Thanks a lot for your work. It will be credited :smiley:

**Pull request merged**
